language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta
cache: cargo
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all --release
  - cargo test --verbose --all -- --nocapture
notification:
  - email: false
